name: Test and Deploy
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Deploy to Google App Engine
      uses: atRobertoFlores/gae_deploy_action@master
      with:
        service_account: duke-re@appspot.gserviceaccount.com
        project_name: duke-re

      env:
        CI: true
        SECRET: 123